Add mouse and home button support, TV output toggle, and automatic connection on startup
GaryOderNichts/moonlight-wiiu pull request #9
Opened 2021-12-25 01:17 UTC by aaronjamt

This PR adds mouse support (with the touchscreen, drag to move mouse and tap to click), forwards the home button (press and hold for 3 seconds to exit). It also skips the "press A to stream/B to pair" screen, instead automatically pairing on startup (if needed), then starting streaming. Finally, it fixes a few minor compiler warnings (due to missing `default:` clauses inside `switch`es) and an error when building if you `#define DEBUG`.

2021-12-25 02:32 UTC, GaryOderNichts requested changes
Thanks a lot for this! The mouse emulation and home button seem to work fine.

Your PR title mentions a "TV output toggle" which I can't find in the code?
Seems good to merge after the few things I mentioned in the review have been fixed.

2021-12-25 02:32 UTC, GaryOderNichts commented on src/main.c
> +  ProcUIClearCallbacks();
Missing include. `ProcUIClearCallbacks` is declared in `proc_ui/procui.h`.

2021-12-25 02:32 UTC, GaryOderNichts commented on src/main.c
> +  while (!server.paired) {
Not a fan of this while loop here. If the server stops or the connection fails, the client is stuck in an endless loop and can't exit.

2021-12-25 02:32 UTC, GaryOderNichts commented on src/wiiu/input.c
> +      sleep(0.1);
`#include <unistd.h>` for `sleep`.

2021-12-25 02:32 UTC, GaryOderNichts commented on src/wiiu/input.c
> +    if (btns & VPAD_BUTTON_HOME && millis() - home_pressed > 3000) wiiu_error_exit("Goodbye!");
You shouldn't use `wiiu_error_exit` to quit the application after the stream has been started. That will forcefully quit the application without properly disconnecting, uninitializing GX2 or freeing memory.

Instead use `WHBProcStopRunning` which will quit out of the main loop.

2021-12-25 02:32 UTC, GaryOderNichts commented on src/main.c
> +#include "wiiu/debug.c"
Why include the C source file here? This will break when linking a DEBUG build.

2021-12-25 02:32 UTC, GaryOderNichts commented on src/wiiu/wiiu.c
> +  WHBProcInit();
I don't think initializing ProcUI again is a good idea.
Maybe re-registering the home button callback which calls `WHBProcStopRunning` would work?

2022-02-06 13:45 UTC, merged

2022-02-06 13:45 UTC, GaryOderNichts commented
Thanks for the PR, decided to rework a lot of moonlight-wiiu and fixed the things I mentioned.

2022-02-23 19:45 UTC, aaronjamt commented
Apologies for the late reply (my Github notifications were disabled for some reason) but thanks for merging this. The TV output toggle thing has to do with the blue "TV" button on the Wii U Gamepad, next to the power button. That commit detects pressing that button and, instead of opening the default "TV control" menu on the gamepad, will toggle whether or not the video feed from Moonlight is sent to the TV output. I had some issues with high latency/slow framerate/dropped connection when it was outputting to the TV as well and my use case only needed it to show on the gamepad. I might have removed that code before commiting since it was specific to my use case.